[phases.setup]
nixPkgs = ['nodejs', 'docker', 'docker-compose']
aptPkgs = ['build-essential', 'python3', 'python3-pip', 'libssl-dev', 'zlib1g-dev', 'pkg-config']

[phases.build]
cmds = [
    "cp .env.example .env",
    "npm install -g pnpm@8.15.5",
    "pnpm install --frozen-lockfile",
    "pnpm run generate",
    "pnpm run build --filter=webapp"
]

[start]
cmd = "cd apps/webapp && pnpm start"

[variables]
NODE_ENV = "production"
PORT = "3000"